name: Kyoshop Monitor

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # ogni ora

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Run monitor
        run: node monitor_kyoshop.js